document.querySelector("#student-btn").addEventListener("click", function () {
  document.querySelector(".signupdiv").innerHTML =
    '<form class="signup_form" action="signup_database.php" method="post"><div class="signup_form-item"><label class="signup_label" for="fname">First Name</label><input class="signup_inputbox" type="text" id="fname" name="fname" placeholder=" First Name" required/></div><div class="signup_form-item"><label class="signup_label" for="lname">Last Name</label><input class="signup_inputbox" type="text" id="lname" name="lname" placeholder=" Last Name" required/></div><div class="signup_form-item"><label class="signup_label" for="userid">Username</label><input class="signup_inputbox" type="text" id="userid" name="userid" placeholder=" Username" required/></div><div class="signup_form-item"><label class="signup_label" for="pwd">Password</label><input class="signup_inputbox" type="password" name="pwd" id="pwd" placeholder=" ***********" required/></div><div class="signup_form-item"><label class="signup_label" for="pwd">Retype Password</label><input class="signup_inputbox" type="password" name="pwd" id="pwd" placeholder=" ***********" required/></div><div class="signup_form-item"><label class="signup_label" for="email">Email</label><input class="signup_inputbox" type="text" name="email" id="email" placeholder=" Email" required/></div><div class="signup_button_div"><input class="signup_button" type="submit" value="SIGN UP" /></div> </form>';
});

document.querySelector("#teacher-btn").addEventListener("click", function () {
  document.querySelector(".signupdiv").innerHTML =
    '<form class="signup_form" action="signup_database.php" method="post"><div class="signup_form-item"><label class="signup_label" for="fname">First Name</label><input class="signup_inputbox" type="text" id="fname" name="fname" placeholder=" First Name" required/></div><div class="signup_form-item"><label class="signup_label" for="lname">Last Name</label><input class="signup_inputbox" type="text" id="lname" name="lname" placeholder=" Last Name" required/></div><div class="signup_form-item"><label class="signup_label" for="userid">Username</label><input class="signup_inputbox" type="text" id="userid" name="userid" placeholder=" Username" required/></div><div class="signup_form-item"><label class="signup_label" for="pwd">Password</label><input class="signup_inputbox" type="password" name="pwd" id="pwd" placeholder=" ***********" required/></div><div class="signup_form-item"><label class="signup_label" for="pwd">Retype Password</label><input class="signup_inputbox" type="password" name="pwd" id="pwd" placeholder=" ***********" required/></div><div class="signup_form-item"><label class="signup_label" for="email">Email</label><input class="signup_inputbox" type="text" name="email" id="email" placeholder=" Email" required/></div><div class="signup_form-item"><label class="signup_label" for="empid">Employee ID</label><input class="signup_inputbox" type="text" name="empid" id="empid" placeholder=" Employee ID" /></div> <div class="signup_form-item"><label class="signup_label" for="uniqid">Unique Identification Number</label><input class="signup_inputbox" type="text" name="uniqid" id="uniqid" placeholder=" Unique Identification Number" required/></div><div class="signup_button_div"><input class="signup_button" type="submit" value="SIGN UP" /></div></form> ';
});
